-- Drop existing tables to rebuild schema cleanly (for dev)
drop table if exists comments;
drop table if exists stories;
drop table if exists profiles;
drop table if exists families;

-- 1. Create Families Table
create table families (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  invite_code text unique not null -- Simple code for joining, e.g., 'X7Y2Z9'
);

alter table families enable row level security;
-- Allow anyone to read families by invite code (to verify it exists before joining)
create policy "Anyone can lookup invite codes" on families for select using (true);
-- Allow authenticated users to create a family
create policy "Auth users can create families" on families for insert with check (auth.role() = 'authenticated');


-- 2. Create Profiles Table (Extended User Info)
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  avatar_url text,
  role text default 'member', -- 'senior', 'family'
  family_id uuid references families(id), -- Nullable initially until they join/create
  
  constraint username_length check (char_length(full_name) >= 2)
);

alter table profiles enable row level security;

create policy "Users can read members of their own family." on profiles
  for select using (
    exists (
      select 1 from profiles my_profile 
      where my_profile.id = auth.uid() 
      and my_profile.family_id = profiles.family_id
    )
    or auth.uid() = id -- Can always read self
  );

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

create policy "Users can insert own profile." on profiles
  for insert with check (auth.uid() = id);


-- 3. Create Stories Table
create table stories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  author_id uuid references auth.users not null,
  family_id uuid references families(id) not null, -- Critical for isolation
  
  author_name text, 
  author_avatar text,
  
  content text,
  audio_text text,
  image_urls text[],
  likes int default 0
);

alter table stories enable row level security;

-- Only users in the SAME family can read stories
create policy "Family members can view stories" on stories
  for select using (
    exists (
      select 1 from profiles 
      where profiles.id = auth.uid() 
      and profiles.family_id = stories.family_id
    )
  );

-- Users can insert stories into THEIR family
create policy "Users can create stories in their family" on stories
  for insert with check (
    auth.uid() = author_id
    and exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.family_id = stories.family_id -- Must match user's family
    )
  );
