-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);


-- Create a table for Stories
create table stories (
  id bigint generated by default as identity primary key,
  author_id uuid references auth.users not null,
  author_name text not null, -- Denormalized for MVP simplicity
  author_avatar text,
  content text,
  audio_text text, -- Text from speech recognition
  image_urls text[], -- Array of image URLs
  likes int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table stories enable row level security;

create policy "Stories are viewable by everyone." on stories
  for select using (true);

create policy "Users can insert their own stories." on stories
  for insert with check (auth.uid() = author_id);
